export const PERMISSIONS = {
  orders: ['orders:read', 'orders:create', 'orders:update', 'orders:delete', 'orders:approve'],
  reports: ['reports:read', 'reports:export', 'reports:generate'],
  stock: ['stock:read', 'stock:manage', 'stock:alert'],
  commissions: ['commissions:read', 'commissions:manage'],
  delivery: ['delivery:read', 'delivery:update', 'delivery:track'],
  customers: ['customers:read', 'customers:create', 'customers:update', 'customers:delete'],
  users: ['users:read', 'users:create', 'users:update', 'users:delete'],
  employees: ['employees:read', 'employees:create', 'employees:update', 'employees:delete'],
  audit: ['audit:read'],
  financial: ['financial:read', 'financial:export'],
  config: ['config:read', 'config:update'],
  alerts: ['alerts:read', 'alerts:manage'],
  sales: ['sales:read', 'sales:create', 'sales:update', 'sales:delete'],
  customOrders: [
    'customOrders:read',
    'customOrders:create',
    'customOrders:update',
    'customOrders:delete',
    'customOrders:transition',
    'customOrders:transition:pendiente_to_aceptado',
    'customOrders:transition:pendiente_to_cancelado',
    'customOrders:transition:en_revision_to_cotizado',
    'customOrders:transition:cotizado_to_cotizacion_aceptada',
    'customOrders:transition:cotizado_to_cotizacion_rechazada',
    'customOrders:transition:pago_aprobado_to_en_produccion',
  ],
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS][number];
