export const adminContent = {
  layout: {
    brandName: import.meta.env.VITE_ADMIN_BRAND_NAME?.trim() || 'SURTI CAMISETAS',
    panelLabel: import.meta.env.VITE_ADMIN_PANEL_LABEL?.trim() || 'Admin Panel',
    userRoleLabels: {
      admin: import.meta.env.VITE_ADMIN_ROLE_ADMIN?.trim() || 'Administrador',
      default: import.meta.env.VITE_ADMIN_ROLE_DEFAULT?.trim() || 'Usuario',
    },
    menu: {
      dashboard: { label: import.meta.env.VITE_ADMIN_MENU_DASHBOARD?.trim() || 'Dashboard General' },
      configuracion: {
        label: import.meta.env.VITE_ADMIN_MENU_CONFIGURACION?.trim() || 'Configuración',
        roles: { label: import.meta.env.VITE_ADMIN_MENU_ROLES?.trim() || 'Roles' },
        permisos: { label: import.meta.env.VITE_ADMIN_MENU_PERMISOS?.trim() || 'Permisos' },
      },
      usuarios: {
        label: import.meta.env.VITE_ADMIN_MENU_USUARIOS?.trim() || 'Usuarios',
        gestionUsuarios: { label: import.meta.env.VITE_ADMIN_MENU_GESTION_USUARIOS?.trim() || 'Gestión de Usuarios' },
        seguridad: { label: import.meta.env.VITE_ADMIN_MENU_SEGURIDAD?.trim() || 'Seguridad' },
        asesores: { label: import.meta.env.VITE_ADMIN_MENU_ASESORES?.trim() || 'Asesores' },
        gestionAcceso: { label: import.meta.env.VITE_ADMIN_MENU_GESTION_ACCESO?.trim() || 'Gestión de Acceso' },
      },
      inventario: {
        label: import.meta.env.VITE_ADMIN_MENU_INVENTARIO?.trim() || 'Existencias',
        productos: { label: import.meta.env.VITE_ADMIN_MENU_PRODUCTOS?.trim() || 'Productos Terminados' },
        insumos: { label: import.meta.env.VITE_ADMIN_MENU_INSUMOS?.trim() || 'Insumos' },
        proveedores: { label: import.meta.env.VITE_ADMIN_MENU_PROVEEDORES?.trim() || 'Proveedores' },
        alertasStock: { label: import.meta.env.VITE_ADMIN_MENU_ALERTAS_STOCK?.trim() || 'Alertas de Stock' },
        stockDevuelto: { label: import.meta.env.VITE_ADMIN_MENU_STOCK_DEVUELTO?.trim() || 'Stock Devuelto' },
      },
      produccion: {
        label: import.meta.env.VITE_ADMIN_MENU_PRODUCCION?.trim() || 'Producción en Talleres Externos',
        talleres: { label: import.meta.env.VITE_ADMIN_MENU_TALLERES?.trim() || 'Registro de Talleres' },
        prendas: { label: import.meta.env.VITE_ADMIN_MENU_PRENDAS?.trim() || 'Control de Prendas' },
        asignacion: { label: import.meta.env.VITE_ADMIN_MENU_ASIGNACION?.trim() || 'Asignación de Producción' },
        seguimiento: { label: import.meta.env.VITE_ADMIN_MENU_SEGUIMIENTO?.trim() || 'Seguimiento' },
      },
      domicilios: { label: import.meta.env.VITE_ADMIN_MENU_DOMICILIOS?.trim() || 'Logística y Domicilios' },
      ventas: {
        label: import.meta.env.VITE_ADMIN_MENU_VENTAS?.trim() || 'Ventas y Pedidos',
        pedidos: { label: import.meta.env.VITE_ADMIN_MENU_PEDIDOS?.trim() || 'Pedidos' },
        facturacion: { label: import.meta.env.VITE_ADMIN_MENU_FACTURACION?.trim() || 'Recibos' },
        pagos: { label: import.meta.env.VITE_ADMIN_MENU_PAGOS?.trim() || 'Pagos' },
        clientes: { label: import.meta.env.VITE_ADMIN_MENU_CLIENTES?.trim() || 'Clientes' },
      },
      reportes: {
        label: import.meta.env.VITE_ADMIN_MENU_REPORTES?.trim() || 'Dashboard de Reportes (Analítica)',
        ventas: { label: import.meta.env.VITE_ADMIN_MENU_REPORTES_VENTAS?.trim() || 'Reportes de Ventas' },
        usuarios: { label: import.meta.env.VITE_ADMIN_MENU_REPORTES_USUARIOS?.trim() || 'Reportes de Usuarios' },
        produccion: { label: import.meta.env.VITE_ADMIN_MENU_REPORTES_PRODUCCION?.trim() || 'Reportes de Producción' },
        inventario: { label: import.meta.env.VITE_ADMIN_MENU_REPORTES_INVENTARIO?.trim() || 'Reportes de Inventario' },
      },
      catalogo: { label: import.meta.env.VITE_ADMIN_MENU_CATALOGO?.trim() || 'Catálogo Digital' },
      webhooks: { label: import.meta.env.VITE_ADMIN_MENU_WEBHOOKS?.trim() || 'Webhooks' },
    },
  },
  dashboard: {
    title: import.meta.env.VITE_ADMIN_DASHBOARD_TITLE?.trim() || 'Dashboard',
    subtitle: import.meta.env.VITE_ADMIN_DASHBOARD_SUBTITLE?.trim() || 'Métricas generales del sistema',
    loading: import.meta.env.VITE_ADMIN_DASHBOARD_LOADING?.trim() || 'Cargando métricas...',
    error: import.meta.env.VITE_ADMIN_DASHBOARD_ERROR?.trim() || 'No se pudieron cargar las métricas del dashboard',
    stats: {
      totalCustomers: import.meta.env.VITE_ADMIN_STAT_TOTAL_CUSTOMERS?.trim() || 'Total Clientes',
      totalOrders: import.meta.env.VITE_ADMIN_STAT_TOTAL_ORDERS?.trim() || 'Pedidos Totales',
      activeProduction: import.meta.env.VITE_ADMIN_STAT_ACTIVE_PRODUCTION?.trim() || 'Producción Activa',
      totalSales: import.meta.env.VITE_ADMIN_STAT_TOTAL_SALES?.trim() || 'Ingresos Totales',
    },
    charts: {
      salesByOrder: import.meta.env.VITE_ADMIN_CHART_SALES_BY_ORDER?.trim() || 'Ventas por pedido',
      orderStatus: import.meta.env.VITE_ADMIN_CHART_ORDER_STATUS?.trim() || 'Estado de Pedidos',
      trendOrders: import.meta.env.VITE_ADMIN_CHART_TREND_ORDERS?.trim() || 'Tendencia Pedidos',
      lowStock: import.meta.env.VITE_ADMIN_CHART_LOW_STOCK?.trim() || 'Productos Bajo Stock',
    },
    tables: {
      recentOrders: import.meta.env.VITE_ADMIN_TABLE_RECENT_ORDERS?.trim() || 'Últimos pedidos',
      recentActivity: import.meta.env.VITE_ADMIN_TABLE_RECENT_ACTIVITY?.trim() || 'Actividad reciente',
      empty: import.meta.env.VITE_ADMIN_TABLE_EMPTY?.trim() || 'No se encontraron pedidos',
      noActivity: import.meta.env.VITE_ADMIN_NO_ACTIVITY?.trim() || 'Sin actividad reciente',
    },
  },
  configuration: {
    title: import.meta.env.VITE_ADMIN_CONFIG_TITLE?.trim() || 'Configuración',
    subtitle: import.meta.env.VITE_ADMIN_CONFIG_SUBTITLE?.trim() || 'Ajustes del sistema y la empresa',
    loading: import.meta.env.VITE_ADMIN_CONFIG_LOADING?.trim() || 'Cargando configuración...',
    empty: import.meta.env.VITE_ADMIN_CONFIG_EMPTY?.trim() || 'No hay configuración disponible',
    save: import.meta.env.VITE_ADMIN_CONFIG_SAVE?.trim() || 'Guardar cambios',
    fallbacks: {
      unavailable: import.meta.env.VITE_ADMIN_CONFIG_FALLBACK_UNAVAILABLE?.trim() || 'No disponible',
      currency: import.meta.env.VITE_ADMIN_CONFIG_FALLBACK_CURRENCY?.trim() || 'COP',
    },
    sectionTitle: import.meta.env.VITE_ADMIN_CONFIG_SECTION_TITLE?.trim() || 'Datos de la Empresa',
    fields: {
      nombre: import.meta.env.VITE_ADMIN_CONFIG_NAME?.trim() || 'Nombre',
      email: import.meta.env.VITE_ADMIN_CONFIG_EMAIL?.trim() || 'Email',
      telefono: import.meta.env.VITE_ADMIN_CONFIG_PHONE?.trim() || 'Teléfono',
      direccion: import.meta.env.VITE_ADMIN_CONFIG_ADDRESS?.trim() || 'Dirección',
      ciudad: import.meta.env.VITE_ADMIN_CONFIG_CITY?.trim() || 'Ciudad',
      nit: import.meta.env.VITE_ADMIN_CONFIG_NIT?.trim() || 'NIT',
      moneda: import.meta.env.VITE_ADMIN_CONFIG_CURRENCY?.trim() || 'Moneda',
    },
    success: import.meta.env.VITE_ADMIN_CONFIG_SUCCESS?.trim() || 'Configuración guardada correctamente',
    error: import.meta.env.VITE_ADMIN_CONFIG_ERROR?.trim() || 'No se pudo guardar la configuración',
  },
  reports: {
    title: import.meta.env.VITE_ADMIN_REPORTS_TITLE?.trim() || 'Reportes',
    subtitle: import.meta.env.VITE_ADMIN_REPORTS_SUBTITLE?.trim() || 'Análisis y reportes del sistema',
    relativeTimes: {
      moment: import.meta.env.VITE_ADMIN_REPORTS_RELATIVE_MOMENT?.trim() || 'Hace un momento',
      minutes: (value: number) => `Hace ${value} min`,
      hours: (value: number) => `Hace ${value} h`,
      days: (value: number) => `Hace ${value} días`,
      yesterday: import.meta.env.VITE_ADMIN_REPORTS_RELATIVE_YESTERDAY?.trim() || 'Ayer',
    },
    searchPlaceholder: import.meta.env.VITE_ADMIN_REPORTS_SEARCH_PLACEHOLDER?.trim() || 'Buscar reportes...',
    filterLabel: import.meta.env.VITE_ADMIN_REPORTS_FILTER_LABEL?.trim() || 'Filtrar por fecha',
    stats: {
      totalSales: import.meta.env.VITE_ADMIN_REPORTS_STAT_TOTAL_SALES?.trim() || 'Ventas Totales',
      completedOrders: import.meta.env.VITE_ADMIN_REPORTS_STAT_COMPLETED_ORDERS?.trim() || 'Pedidos Completados',
      newCustomers: import.meta.env.VITE_ADMIN_REPORTS_STAT_NEW_CUSTOMERS?.trim() || 'Clientes Nuevos',
      averageTicket: import.meta.env.VITE_ADMIN_REPORTS_STAT_AVERAGE_TICKET?.trim() || 'Ticket Promedio',
    },
    charts: {
      salesByStatus: import.meta.env.VITE_ADMIN_REPORTS_CHART_SALES_STATUS?.trim() || 'Ventas por Estado',
      monthlyTrend: import.meta.env.VITE_ADMIN_REPORTS_CHART_MONTHLY_TREND?.trim() || 'Tendencia Mensual',
      rankingAsesores: import.meta.env.VITE_ADMIN_REPORTS_CHART_RANKING_ASESORES?.trim() || 'Ranking de Asesores',
      topProducts: import.meta.env.VITE_ADMIN_REPORTS_CHART_TOP_PRODUCTS?.trim() || 'Productos Top',
    },
    table: {
      generatedReports: import.meta.env.VITE_ADMIN_REPORTS_TABLE_TITLE?.trim() || 'Reportes Generados',
      id: import.meta.env.VITE_ADMIN_REPORTS_TABLE_ID?.trim() || 'ID',
      title: import.meta.env.VITE_ADMIN_REPORTS_TABLE_TITLE_COL?.trim() || 'Título',
      period: import.meta.env.VITE_ADMIN_REPORTS_TABLE_PERIOD?.trim() || 'Periodo',
      generated: import.meta.env.VITE_ADMIN_REPORTS_TABLE_GENERATED?.trim() || 'Generado',
      status: import.meta.env.VITE_ADMIN_REPORTS_TABLE_STATUS?.trim() || 'Estado',
      actions: import.meta.env.VITE_ADMIN_REPORTS_TABLE_ACTIONS?.trim() || 'Acciones',
      download: import.meta.env.VITE_ADMIN_REPORTS_DOWNLOAD?.trim() || 'Descargar',
      empty: import.meta.env.VITE_ADMIN_REPORTS_EMPTY?.trim() || 'No se encontraron reportes',
    },
    states: {
      available: import.meta.env.VITE_ADMIN_REPORTS_STATE_AVAILABLE?.trim() || 'Disponible',
      noPeriod: import.meta.env.VITE_ADMIN_REPORTS_NO_PERIOD?.trim() || 'Periodo no disponible',
      loading: import.meta.env.VITE_ADMIN_REPORTS_LOADING?.trim() || 'Cargando...',
      retry: import.meta.env.VITE_ADMIN_REPORTS_RETRY?.trim() || 'Reintentar',
    },
  },
};
