import type { CustomOrderEstado } from '@/infrastructure/api/customOrdersApi';

export const CUSTOM_ORDER_STATUS_TRANSITIONS: Record<CustomOrderEstado, CustomOrderEstado[]> = {
  PENDIENTE: ['ACEPTADO', 'CANCELADO'],
  ACEPTADO: ['CANCELADO'],
  CANCELADO: [],
  SOLICITUD_RECIBIDA: ['ACEPTADO', 'CANCELADO'],
  EN_REVISION: ['CANCELADO'],
  COTIZADO: ['COTIZACION_ACEPTADA', 'COTIZACION_RECHAZADA', 'CANCELADO'],
  COTIZACION_ACEPTADA: ['PAGO_PENDIENTE', 'CANCELADO'],
  COTIZACION_RECHAZADA: ['SOLICITUD_RECIBIDA', 'CANCELADO'],
  PAGO_PENDIENTE: ['PAGO_EN_VERIFICACION', 'CANCELADO'],
  PAGO_EN_VERIFICACION: ['PAGO_APROBADO', 'CANCELADO'],
  PAGO_APROBADO: ['CONVERTIDO_A_PEDIDO', 'EN_PRODUCCION', 'CANCELADO'],
  EN_PRODUCCION: ['COMPLETADO', 'CANCELADO'],
  COMPLETADO: [],
  CONVERTIDO_A_PEDIDO: [],
  VENCIDO: [],
};